Members-only Project
GraceOyiza/members-only pull request #2
Opened 2020-11-13 10:38 UTC by GraceOyiza

- All required changes fixed

2020-11-13 11:42 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Remove the `README` title in readme.md file
- [ ] Pull Request should have a meaningful description
- [ ] Lets remove commented codes
- [ ] Logout should display only when user is logged in
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-11-13 11:42 UTC, kobiyoyo commented on app/views/posts/index.html.erb
> +<% end %>
- [ ] Please remove all logic from your views. There should be absolutely no logic in views. Instead, use helper methods to outsource view logic.

2020-11-13 11:42 UTC, kobiyoyo commented on app/controllers/posts_controller.rb
> +    puts current_user.id
Please remove this, as it is not required in this application.

2020-11-13 13:57 UTC, GraceOyiza commented
- This project is about members authentication, Post and User models. 
- The association between the post and user were defined.

2020-11-13 14:20 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] Logout should display only when user is logged in (its the same implementation for author)
- check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-11-13 14:20 UTC, kobiyoyo commented on app/helpers/posts_helper.rb
> +  end
- [ ] Kindly remove this as you already have it in controllers

2020-11-13 14:23 UTC, kobiyoyo commented on app/models/user.rb
> +  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
- [ ] Lets delete this commented code

2020-11-13 16:48 UTC, GraceOyiza commented
- All required errors fixed

2020-11-13 17:13 UTC, tirthajyoti-ghosh approved these changes
# Approved ✅

## You have done an incredible job making this project 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of the project. Go ahead and merge it! Onto the next project 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-11-14 07:21 UTC, Alaska01 commented
Project has been approved!!!!

2020-11-14 07:21 UTC, merged